In [5]:
import fer_config as config
import os
os.path.join(config.MODEL_SAVE_PATH, config.MODEL_NAME+'_'+str(1))

'/home/ubuntu/user_space/model/fer/fer_model_1'

In [2]:
from PIL import Image
import numpy as np
im_path = './test_img.PNG'
im1 = Image.open(im_path)
im1
img_array1=np.asarray(im1)
img_array2=np.array(im1)
img_array1
img_array2
list_ = [[[222, 222, 222, 255],
        [240, 240, 240, 255],
        [230, 231, 234, 255],
        [206, 211, 213, 255],
        [202, 209, 209, 255]],

       [[223, 223, 223, 255],
        [240, 240, 240, 255],
        [240, 240, 240, 255],
        [238, 239, 239, 255],
        [238, 239, 239, 255]],

       [[223, 223, 223, 255],
        [240, 240, 240, 255],
        [240, 240, 240, 255],
        [240, 240, 240, 255],
        [240, 240, 240, 255]]]
list_array = np.array(list_)
list_array, img_array2

(array([[[222, 222, 222, 255],
         [240, 240, 240, 255],
         [230, 231, 234, 255],
         [206, 211, 213, 255],
         [202, 209, 209, 255]],

        [[223, 223, 223, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [238, 239, 239, 255],
         [238, 239, 239, 255]],

        [[223, 223, 223, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255]]]), array([[[222, 222, 222, 255],
         [240, 240, 240, 255],
         [230, 231, 234, 255],
         [206, 211, 213, 255],
         [202, 209, 209, 255]],

        [[223, 223, 223, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [238, 239, 239, 255],
         [238, 239, 239, 255]],

        [[223, 223, 223, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255],
         [240, 240, 240, 255]]], dtype=uint8))

In [3]:
import fer_config as config
import pandas as pd
import numpy as np
def read_data(path):
    data = pd.read_csv(path)
    images=[np.array(p.split(" "),dtype=int) for p in data["pixels"]]
    labels=data["emotion"]
    return images,labels

In [ ]:
images_train, labels_train=read_data(config.train_data_path)
images_train

In [6]:
testpath = './test.csv'
# pandas的DataFrame有to_csv这个方法
pixels = list(img_array2)

df=pd.DataFrame(data={"pixels":[pixels,pixels],"emotion":[2,6]},
                           columns=["pixels","emotion"])
image_arr_uint8 = np.array(images[i],dtype='uint8')
                image = Image.fromarray(np.reshape(image_arr_uint8, (config.img_width, config.img_height))).convert('L')
df.to_csv(testpath, header=False)

In [26]:
ar = np.array([1,2,3,4,5,6])
w = 2
h = 3
ar2 = np.reshape(ar,(w,h))
ar3 = np.reshape(ar2,(6,1))
list(ar2)
ar2.tolist()
ar3 = np.reshape(ar2,6)
ar3
ar2.reshape(6)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
df

                                              pixels  emotion
0  [[[222, 222, 222, 255], [240, 240, 240, 255], ...        2
1  [[[222, 222, 222, 255], [240, 240, 240, 255], ...        6

In [21]:
data = pd.read_csv(config.data_path)
images = data["pixels"]
labels = data["emotion"]
usages = data["Usage"]

0        70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...
1        151 150 147 155 148 133 111 140 170 174 182 15...
2        231 212 156 164 174 138 161 173 182 200 106 38...
3        24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...
4        4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...
5        55 55 55 55 55 54 60 68 54 85 151 163 170 179 ...
6        20 17 19 21 25 38 42 42 46 54 56 62 63 66 82 1...
7        77 78 79 79 78 75 60 55 47 48 58 73 77 79 57 5...
8        85 84 90 121 101 102 133 153 153 169 177 189 1...
9        255 254 255 254 254 179 122 107 95 124 149 150...
10       30 24 21 23 25 25 49 67 84 103 120 125 130 139...
11       39 75 78 58 58 45 49 48 103 156 81 45 41 38 49...
12       219 213 206 202 209 217 216 215 219 218 223 23...
13       148 144 130 129 119 122 129 131 139 153 140 12...
14       4 2 13 41 56 62 67 87 95 62 65 70 80 107 127 1...
15       107 107 109 109 109 109 110 101 123 140 144 14...
16       14 14 18 28 27 22 21 30 42 61 77 86 88 95 100 ...
17       255 255 255 255 255 255 255 255 255 255 255 25...
18       134 124 167 180 197 194 203 210 204 203 209 20...
19       219 192 179 148 208 254 192 98 121 103 145 185...
20       1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 7 12 23 45 38 ...
21       174 51 37 37 38 41 22 25 22 24 35 51 70 83 98 ...
22       123 125 124 142 209 226 234 236 231 232 235 22...
23       8 9 14 21 26 32 37 46 52 62 72 70 71 73 76 83 ...
24       252 250 246 229 182 140 98 72 53 44 67 95 95 8...
25       224 227 219 217 215 210 187 177 189 200 206 21...
26       162 200 187 180 197 198 196 192 176 152 136 11...
27       236 230 225 226 228 209 199 193 196 211 199 19...
28       210 210 210 210 211 207 147 103 68 60 47 70 12...
29       50 44 74 141 187 187 169 113 80 128 181 172 76...
                               ...
35857    253 255 229 150 89 61 54 60 55 49 61 50 56 45 ...
35858    11 11 11 13 20 27 38 41 38 34 20 13 10 39 85 1...
35859    11 13 16 27 24 26 89 161 190 197 201 206 210 2...
35860    27 42 62 91 112 118 122 123 119 124 129 131 13...
35861    233 232 208 188 194 179 177 167 157 180 185 19...
35862    73 54 63 76 82 71 67 69 73 72 92 98 117 119 14...
35863    196 196 197 197 198 198 198 196 176 148 122 10...
35864    68 59 65 78 118 131 137 141 142 135 135 137 13...
35865    102 109 109 106 104 107 112 109 116 119 117 12...
35866    87 82 59 61 72 102 143 130 90 95 143 173 146 1...
35867    198 198 197 196 196 197 196 196 196 195 196 18...
35868    204 209 215 218 214 214 214 217 205 175 170 16...
35869    217 220 222 223 223 224 225 223 223 225 223 22...
35870    6 8 4 5 30 48 61 70 76 79 98 117 130 137 143 1...
35871    112 102 98 89 98 133 164 185 180 179 185 169 1...
35872    131 159 90 59 10 0 1 1 1 0 1 1 0 0 2 2 5 7 9 1...
35873    54 57 77 122 121 76 73 80 58 22 26 27 35 41 66...
35874    43 43 51 73 94 97 102 95 99 107 126 144 154 17...
35875    248 251 239 144 102 95 82 77 91 138 153 145 14...
35876    29 29 27 31 49 56 29 19 22 20 34 43 55 71 85 9...
35877    139 143 145 154 159 168 176 181 190 191 195 19...
35878    0 39 81 80 104 97 51 64 68 46 41 67 53 68 70 5...
35879    0 0 6 16 19 31 47 18 26 19 17 8 15 3 4 2 14 20...
35880    164 172 175 171 172 173 178 181 188 192 197 20...
35881    181 177 176 156 178 144 136 132 122 107 131 16...
35882    50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...
35883    178 174 172 173 181 188 191 194 196 199 200 20...
35884    17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...
35885    30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...
35886    19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...
Name: pixels, Length: 35887, dtype: object

In [22]:
data

       emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
5            2  55 55 55 55 55 54 60 68 54 85 151 163 170 179 ...     Training
6            4  20 17 19 21 25 38 42 42 46 54 56 62 63 66 82 1...     Training
7            3  77 78 79 79 78 75 60 55 47 48 58 73 77 79 57 5...     Training
8            3  85 84 90 121 101 102 133 153 153 169 177 189 1...     Training
9            2  255 254 255 254 254 179 122 107 95 124 149 150...     Training
10           0  30 24 21 23 25 25 49 67 84 103 120 125 130 139...     Training
11           6  39 75 78 58 58 45 49 48 103 156 81 45 41 38 49...     Training
12           6  219 213 206 202 209 217 216 215 219 218 223 23...     Training
13           6  148 144 130 129 119 122 129 131 139 153 140 12...     Training
14           3  4 2 13 41 56 62 67 87 95 62 65 70 80 107 127 1...     Training
15           5  107 107 109 109 109 109 110 101 123 140 144 14...     Training
16           3  14 14 18 28 27 22 21 30 42 61 77 86 88 95 100 ...     Training
17           2  255 255 255 255 255 255 255 255 255 255 255 25...     Training
18           6  134 124 167 180 197 194 203 210 204 203 209 20...     Training
19           4  219 192 179 148 208 254 192 98 121 103 145 185...     Training
20           4  1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 7 12 23 45 38 ...     Training
21           2  174 51 37 37 38 41 22 25 22 24 35 51 70 83 98 ...     Training
22           0  123 125 124 142 209 226 234 236 231 232 235 22...     Training
23           0  8 9 14 21 26 32 37 46 52 62 72 70 71 73 76 83 ...     Training
24           3  252 250 246 229 182 140 98 72 53 44 67 95 95 8...     Training
25           3  224 227 219 217 215 210 187 177 189 200 206 21...     Training
26           5  162 200 187 180 197 198 196 192 176 152 136 11...     Training
27           0  236 230 225 226 228 209 199 193 196 211 199 19...     Training
28           3  210 210 210 210 211 207 147 103 68 60 47 70 12...     Training
29           5  50 44 74 141 187 187 169 113 80 128 181 172 76...     Training
...        ...                                                ...          ...
35857        5  253 255 229 150 89 61 54 60 55 49 61 50 56 45 ...  PrivateTest
35858        4  11 11 11 13 20 27 38 41 38 34 20 13 10 39 85 1...  PrivateTest
35859        4  11 13 16 27 24 26 89 161 190 197 201 206 210 2...  PrivateTest
35860        3  27 42 62 91 112 118 122 123 119 124 129 131 13...  PrivateTest
35861        6  233 232 208 188 194 179 177 167 157 180 185 19...  PrivateTest
35862        2  73 54 63 76 82 71 67 69 73 72 92 98 117 119 14...  PrivateTest
35863        5  196 196 197 197 198 198 198 196 176 148 122 10...  PrivateTest
35864        4  68 59 65 78 118 131 137 141 142 135 135 137 13...  PrivateTest
35865        3  102 109 109 106 104 107 112 109 116 119 117 12...  PrivateTest
35866        6  87 82 59 61 72 102 143 130 90 95 143 173 146 1...  PrivateTest
35867        3  198 198 197 196 196 197 196 196 196 195 196 18...  PrivateTest
35868        2  204 209 215 218 214 214 214 217 205 175 170 16...  PrivateTest
35869        3  217 220 222 223 223 224 225 223 223 225 223 22...  PrivateTest
35870        2  6 8 4 5 30 48 61 70 76 79 98 117 130 137 143 1...  PrivateTest
35871        6  112 102 98 89 98 133 164 185 180 179 185 169 1...  PrivateTest
35872        5  131 159 90 59 10 0 1 1 1 0 1 1 0 0 2 2 5 7 9 1...  PrivateTest
35873        4  54 57 77 122 121 76 73 80 58 22 26 27 35 41 66...  PrivateTest
35874        5  43 43 51 73 94 97 102 95 99 107 126 144 154 17...  PrivateTest
35875        5  248 251 239 144 102 95 82 77 91 138 153 145 14...  PrivateTest
35876        6  29 29 27 31 49 56 29 19 22 20 34 43 55 71 85 9...  PrivateTest
35877        6  139 143 145 154 159 168 176 181 190 191 195 19...  PrivateTest
35878        3  0 39 81 80 104 97 51 64 68 46 41 67 53 68 70 5...  PrivateTest
35879        2  0 0 6 16 19 31 47 18 26 19 17 8 15 3 4 2 14 20...  PrivateTest
35880        2  164 172 175 171 172 173 178 181 188 192 197 20...  PrivateTest
35881        0  181 177 176 156 178 144 136 132 122 107 131 16...  PrivateTest
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 columns]

In [28]:
img_valid = []
label_valid = []
for i in range(len(images)):
    if usages[i]=="PrivateTest":
        img_valid.append(images[i])
        label_valid.append(labels[i])

In [27]:
type(images)

pandas.core.series.Series

In [29]:
type(img_valid)

list

In [32]:
data_valid = pd.DataFrame(data={"pixels": img_valid, "emotion": label_valid},
                              columns=["pixels", "emotion"])
data_valid.to_csv(testpath, encoding="utf_8_sig", index=False)
data_valid

                                                 pixels  emotion
0     170 118 101 88 88 75 78 82 66 74 68 59 63 64 6...        0
1     7 5 8 6 7 3 2 6 5 4 4 5 7 5 5 5 6 7 7 7 10 10 ...        5
2     232 240 241 239 237 235 246 117 24 24 22 13 12...        6
3     200 197 149 139 156 89 111 58 62 95 113 117 11...        4
4     40 28 33 56 45 33 31 78 152 194 200 186 196 20...        2
5     138 142 66 80 87 92 97 99 88 73 72 83 92 102 1...        0
6     72 66 66 69 62 51 57 60 56 66 63 70 68 68 81 9...        4
7     4 4 7 12 14 18 26 31 33 38 44 49 59 68 80 86 9...        3
8     245 245 239 122 144 101 33 37 84 137 143 130 1...        0
9     20 31 65 81 79 63 61 51 61 97 114 121 140 200 ...        3
10    255 255 255 252 255 212 122 107 137 178 196 21...        5
11    245 247 243 242 233 229 213 190 173 141 109 13...        3
12    60 41 21 35 43 50 49 54 56 62 68 75 82 87 93 9...        4
13    190 192 198 197 189 184 168 142 105 107 156 16...        4
14    215 218 222 220 221 226 218 215 216 218 218 21...        0
15    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...        6
16    133 140 138 137 136 133 130 124 114 105 115 11...        2
17    124 141 120 113 105 106 114 103 91 109 105 105...        5
18    253 253 253 252 253 252 254 253 252 248 244 24...        4
19    102 102 103 102 102 103 103 103 103 102 110 10...        2
20    221 177 138 120 110 90 84 82 86 101 104 91 79 ...        3
21    22 18 17 17 26 35 26 18 22 22 18 19 14 22 24 2...        6
22    58 52 55 62 59 42 40 45 43 39 40 43 46 46 56 7...        0
23    77 79 75 74 79 85 85 80 139 214 212 187 190 20...        6
24    134 133 144 180 186 201 158 146 156 154 169 17...        3
25    74 83 91 98 101 106 116 118 124 132 135 136 14...        2
26    74 93 94 102 113 148 160 169 155 163 145 128 1...        5
27    186 184 186 185 176 174 177 171 171 176 169 15...        6
28    145 146 118 26 15 18 16 18 24 38 57 66 71 78 8...        6
29    78 47 47 56 87 155 186 198 200 195 196 196 192...        3
...                                                 ...      ...
3559  253 255 229 150 89 61 54 60 55 49 61 50 56 45 ...        5
3560  11 11 11 13 20 27 38 41 38 34 20 13 10 39 85 1...        4
3561  11 13 16 27 24 26 89 161 190 197 201 206 210 2...        4
3562  27 42 62 91 112 118 122 123 119 124 129 131 13...        3
3563  233 232 208 188 194 179 177 167 157 180 185 19...        6
3564  73 54 63 76 82 71 67 69 73 72 92 98 117 119 14...        2
3565  196 196 197 197 198 198 198 196 176 148 122 10...        5
3566  68 59 65 78 118 131 137 141 142 135 135 137 13...        4
3567  102 109 109 106 104 107 112 109 116 119 117 12...        3
3568  87 82 59 61 72 102 143 130 90 95 143 173 146 1...        6
3569  198 198 197 196 196 197 196 196 196 195 196 18...        3
3570  204 209 215 218 214 214 214 217 205 175 170 16...        2
3571  217 220 222 223 223 224 225 223 223 225 223 22...        3
3572  6 8 4 5 30 48 61 70 76 79 98 117 130 137 143 1...        2
3573  112 102 98 89 98 133 164 185 180 179 185 169 1...        6
3574  131 159 90 59 10 0 1 1 1 0 1 1 0 0 2 2 5 7 9 1...        5
3575  54 57 77 122 121 76 73 80 58 22 26 27 35 41 66...        4
3576  43 43 51 73 94 97 102 95 99 107 126 144 154 17...        5
3577  248 251 239 144 102 95 82 77 91 138 153 145 14...        5
3578  29 29 27 31 49 56 29 19 22 20 34 43 55 71 85 9...        6
3579  139 143 145 154 159 168 176 181 190 191 195 19...        6
3580  0 39 81 80 104 97 51 64 68 46 41 67 53 68 70 5...        3
3581  0 0 6 16 19 31 47 18 26 19 17 8 15 3 4 2 14 20...        2
3582  164 172 175 171 172 173 178 181 188 192 197 20...        2
3583  181 177 176 156 178 144 136 132 122 107 131 16...        0
3584  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...        6
3585  178 174 172 173 181 188 191 194 196 199 200 20...        3
3586  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...        0
3587  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...        3
3588  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...        2

[3589 rows x 2 columns]